name: github-env

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: context
      env:
        COMMIT_ID: ${{ github.sha }}
      run:
        echo "Commit Id => COMMIT_ID"
